###
GET http://localhost/api_back/getuserlist/

###
POST  http://localhost/api_back/

# ligne 9 à 11 c'est du code format json

{
    "pseudo": "BG",
    "password" :"passer",
    "action" : "login"
}

###
POST  http://localhost/api_back/

{
    "pseudo": "Faissal",
    "password" :"passer",
    "firstname" :"C'est quoi ta note",
    "lastname" :"ta note ???",
    "action" : "register"
}

###
POST  http://localhost/api_back/

{
    "expeditor": 71,
    "receiver": 59,
    "message" :"je ne sais pas j'ai peur",
    "action" : "send message"
}

###
GET  http://localhost/api_back/getListMessage/71/59

